dist: bionic
osx_image: xcode10.3
sudo: required
language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - "node"
#  - "lts/dubnium"
cache: npm
script:
  - perl -v
  - npm run test
  - "[[ ${TRAVIS_NODE_VERSION} != node ]] || ( npx electron-rebuild && npx xvfb-maybe electron-mocha --file test/vdf.js )"
addons:
  homebrew:
    packages:
    - openssl@1.1
    update: true
  apt:
    packages:
    - libssl-dev
    update: true
jobs:
  include:
    - stage: coverage
      node_js: "lts/dubnium"
      os: linux
      script:
       - npm run lint
       - npm run coverage && npx coveralls < coverage/lcov.info
